Author extension
open-contracting-extensions/ocds_contract_period_description_extension pull request #1
Opened 2023-05-30 00:30 UTC by duncandewhurst

2023-05-30 00:31 UTC, duncandewhurst commented
@jpmckinney I accidentally created this repository under the open-contracting organisation. Please could you transfer it to the open-contracting-extensions organisation so that I can request a review from Jen? Thanks!

2023-05-30 00:42 UTC, jpmckinney commented
Transferred!

2023-05-30 00:45 UTC, duncandewhurst commented
Great. Thanks!

2023-06-02 10:19 UTC, odscjen requested changes
Looks good. Just one thing, a lot of the other extensions include a line at the bottom of the README pointing towards the original discussion issues and PR's. Should this also have one? e.g.

"This extension was originally discussed as part of the [OCDS for eForms](https://github.com/open-contracting-extensions/european-union/issues/70) and in [pull requests](https://github.com/open-contracting-extensions/ocds_contract_period_description_extension/pulls)."

2023-06-07 05:05 UTC, duncandewhurst commented
@jpmckinney should we add the sentence that Jen suggested to all of the new extensions?

2023-06-07 17:18 UTC, jpmckinney commented
For the new extensions for eForms, the discussion has been much more centralized (i.e. european-union-support and the extension's PRs). So, I don't think we need to add this content.

With OCDS for EU, I think it was a bit more spread out at times (european-union profile issues, standard issues, ocds-extensions issues, etc.), so it was more useful to add some links.

2023-06-07 23:11 UTC, duncandewhurst commented
Sounds good.

2023-06-08 21:30 UTC, jpmckinney approved these changes

2023-06-08 21:30 UTC, jpmckinney commented on README.md
> +Adds a description field to the `Period` object to describe periods that are unknown, unlimited or otherwise not able to be expressed using the object's other fields.
In the first sentence we typically avoid formatted text (so that it's often the same plain-text in the extension metadata and GitHub description).

```suggestion
Adds a description field to the period object to describe periods that are unknown, unlimited or otherwise not able to be expressed using the object's other fields.
```

2023-06-08 21:30 UTC, jpmckinney commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BT-538 (Duration Other)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eForms fields
```suggestion
In the European Union, this extension's fields correspond to [eForms BT-538 (Duration Other)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/).  See [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/en/) for the correspondences to eForms fields.
```

2023-06-08 21:33 UTC, jpmckinney approved these changes
Just wondering why we made a single-field extension instead of adding this to the EU extension?

I can't remember. I do see it is as a new extension in the [spreadsheet](https://docs.google.com/spreadsheets/d/1VIAFbuTCF1kMhP7ngWnlFrE9HXSUb6I6W8emlkUy3K8/edit#gid=1619313430).

2023-06-14 01:28 UTC, duncandewhurst commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BT-538 (Duration Other)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eForms fields
Interested to know why you prefer this construction. I used the former construction here and elsewhere, on the basis that it puts the information that the reader needs to decide if the link is relevant to them before the link itself.

2023-06-14 01:32 UTC, duncandewhurst commented
Looks like I proposed creating a new extension in the spreadsheet. I don't remember why, but I guess it was because I thought it didn't fit into any existing extensions and it is a generally applicable, rather than EU-specific, concept. That latter point is debatable, though, so I'm happy to move it to the EU extension if you think that would be better.

2023-06-14 01:47 UTC, jpmckinney commented
I think I prefer putting it in the EU extension, because modifying a core subschema like Period is somewhat unusual (given that it affects every period, not just the one we want to target), so better to limit it to the EU extension, I think.

2023-06-19 04:13 UTC, duncandewhurst commented
Draft PR for the eu extension: https://github.com/open-contracting-extensions/ocds_eu_extension/pull/13 (I forgot the eforms PR was still open...)

> modifying a core subschema like Period is somewhat unusual (given that it affects every period, not just the one we want to target)

From a JSON schema point of view, I think the extra property could be added to `definitions/Tender/properties/contractPeriod/properties` and the same for `Lot` so that it only appears in those contexts, but I'm not sure how docson or the jsonschema Sphinx directives would handle the combination of a `$ref` and `properties`.

2023-06-19 21:24 UTC, duncandewhurst commented
Ah, I see that is the case in draft 4 but changed from draft 2019-09 onwards to allows keywords alongside `$ref` as a shorthand to putting two schemas inside an `allOf`.

2023-06-19 21:26 UTC, duncandewhurst commented
Anyway, I'll close this PR and archive the repo in favour of https://github.com/open-contracting-extensions/ocds_eu_extension/pull/13

2023-06-19 21:26 UTC, closed without merging